// Generated by ReScript, PLEASE EDIT WITH CARE

import * as WorkerGlobalScope$WebAPIWebWorkers from "./WorkerGlobalScope.js";

function Impl(T) {
  WorkerGlobalScope$WebAPIWebWorkers.Impl({});
  return {};
}

WorkerGlobalScope$WebAPIWebWorkers.Impl({});

export {
  Impl,
}
/*  Not a pure module */
