// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Element$DOM from "@rescript-webapi/dom/src/Element.js";
import * as Document$DOM from "@rescript-webapi/dom/src/Document.js";

function decode(t) {
  if (Element$DOM.isInstanceOf(t)) {
    return {
      TAG: "Element",
      _0: t
    };
  } else if (Document$DOM.isInstanceOf(t)) {
    return {
      TAG: "Document",
      _0: t
    };
  } else {
    return "Null";
  }
}

export {
  decode,
}
/* Element-DOM Not a pure module */
