// Generated by ReScript, PLEASE EDIT WITH CARE

import * as WorkerGlobalScope$WebWorkers from "@rescript-webapi/web-workers/src/WorkerGlobalScope.js";

WorkerGlobalScope$WebWorkers.Impl({});

/*  Not a pure module */
