// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Element$WebAPI from "./Element.js";

function Impl(T) {
  Element$WebAPI.Impl({});
  return {};
}

Element$WebAPI.Impl({});

export {
  Impl,
}
/*  Not a pure module */
