// Generated by ReScript, PLEASE EDIT WITH CARE

import * as WorkerGlobalScope$WebAPIWebWorkers from "@rescript/webapi-web-workers/src/WorkerGlobalScope.js";

WorkerGlobalScope$WebAPIWebWorkers.Impl({});

/*  Not a pure module */
