// Generated by ReScript, PLEASE EDIT WITH CARE

import * as WorkerGlobalScope$WebWorkers from "./WorkerGlobalScope.js";

function Impl(T) {
  WorkerGlobalScope$WebWorkers.Impl({});
  return {};
}

WorkerGlobalScope$WebWorkers.Impl({});

export {
  Impl,
}
/*  Not a pure module */
