// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EventTarget$Event from "@rescript-webapi/event/src/EventTarget.js";

function Impl(T) {
  EventTarget$Event.Impl({});
  return {};
}

EventTarget$Event.Impl({});

export {
  Impl,
}
/*  Not a pure module */
