// Generated by ReScript, PLEASE EDIT WITH CARE


let response = await fetch("https://rescript-lang.org/");

let response2 = await fetch("https://rescript-lang.org/", {
  headers: {
    "Content-Type": "application/json",
    Authorization: "Bearer token"
  },
  body: "secret=foo&response=bar"
});

let response3 = await fetch(new Request("https://rescript-lang.org/"), {
  method: "POST",
  headers: {
    "Content-Type": "application/x-www-form-urlencoded"
  },
  body: "secret=foo&response=bar"
});

removeEventListener("mousedown", prim => {
  prim.preventDefault();
}, {
  capture: false
});

let registrationResult = await navigator.serviceWorker.register("/sw.js");

export {
  response,
  response2,
  response3,
  registrationResult,
}
/* response Not a pure module */
