// Generated by ReScript, PLEASE EDIT WITH CARE


let response = await fetch("https://rescript-lang.org/");

let response2 = await fetch("https://rescript-lang.org/", {
  headers: {
    "Content-Type": "application/json",
    Authorization: "Bearer token"
  },
  body: `secret=foo&response=bar`
});

let response3 = await fetch(new Request("https://rescript-lang.org/"), {
  method: "POST",
  headers: {
    "Content-Type": "application/x-www-form-urlencoded"
  },
  body: `secret=foo&response=bar`
});

removeEventListener("mousedown", prim => {
  prim.preventDefault();
}, {
  capture: false
});

let registrationResult = await navigator.serviceWorker.register("/sw.js");

let subscription = await registrationResult.pushManager.subscribe({
  userVisibleOnly: true,
  applicationServerKey: "MyPublicKey"
});

let pushSubscriptionJSON = subscription.toJSON();

let keys = pushSubscriptionJSON.keys;

let match = keys !== undefined ? [
    keys.auth,
    keys.p256dh
  ] : [
    "?",
    "?"
  ];

let p256dh = match[1];

let auth = match[0];

console.log(`For subscription ` + subscription.endpoint + `, auth is ` + auth + ` and p256dh is ` + p256dh);

export {
  response,
  response2,
  response3,
  registrationResult,
  subscription,
  pushSubscriptionJSON,
  auth,
  p256dh,
}
/* response Not a pure module */
