// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";
import * as IntersectionObserverRoot$WebAPI from "../../src/IntersectionObserverAPI/IntersectionObserverRoot.js";

let observer = new IntersectionObserver((entry, observer) => {
  console.log(entry, observer);
});

let root = document.querySelector("#root");

let observer2 = new IntersectionObserver((entry, observer) => {
  console.log(entry, observer);
}, {
  root: Primitive_option.some(root),
  rootMargin: "10px",
  threshold: [0.1]
});

let match = IntersectionObserverRoot$WebAPI.decode(observer2.root);

if (typeof match !== "object") {
  console.log("Null");
} else if (match.TAG === "Element") {
  console.log("Element");
} else {
  console.log("Document");
}

let rootMargin2 = observer2.rootMargin;

let targetElement = document.querySelector("#targetElement");

if (targetElement !== null) {
  observer2.observe(targetElement);
  observer2.unobserve(targetElement);
} else {
  console.log("Target element not found.");
}

let entries2 = observer2.takeRecords();

console.log(entries2.length);

observer2.disconnect();

let targetElement$1 = targetElement === null ? undefined : Primitive_option.some(targetElement);

export {
  observer,
  root,
  observer2,
  rootMargin2,
  targetElement$1 as targetElement,
  entries2,
}
/* observer Not a pure module */
