// Generated by ReScript, PLEASE EDIT WITH CARE


let shared1 = new SharedWorker("sharedworker.js");

let shared2 = new SharedWorker("sharedworker.js", "name");

let shared3 = new SharedWorker("sharedworker.js", {
  type: "module",
  name: "workerName"
});

let port = shared1.port;

let self = self();

self.close();

export {
  shared1,
  shared2,
  shared3,
  port,
  self,
}
/* shared1 Not a pure module */
