// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AudioNode$WebAPI from "./AudioNode.js";

function Impl(T) {
  AudioNode$WebAPI.Impl({});
  return {};
}

AudioNode$WebAPI.Impl({});

export {
  Impl,
}
/*  Not a pure module */
