// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AudioNode$WebApi from "./AudioNode.js";

function Impl(T) {
  AudioNode$WebApi.Impl({});
  return {};
}

AudioNode$WebApi.Impl({});

export {
  Impl,
}
/*  Not a pure module */
