// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EventTarget$WebApi from "../EventAPI/EventTarget.js";

function Impl(T) {
  EventTarget$WebApi.Impl({});
  return {};
}

export {
  Impl,
}
/* No side effect */
