// Generated by ReScript, PLEASE EDIT WITH CARE

import * as UIEvent$WebAPIUIEvents from "./UIEvent.js";

function Impl(T) {
  UIEvent$WebAPIUIEvents.Impl({});
  return {};
}

UIEvent$WebAPIUIEvents.Impl({});

export {
  Impl,
}
/*  Not a pure module */
