// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Event$WebAPI from "@rescript/webapi/src/Event.js";

function Impl(T) {
  Event$WebAPI.Impl({});
  return {};
}

Event$WebAPI.Impl({});

export {
  Impl,
}
/*  Not a pure module */
