// Generated by ReScript, PLEASE EDIT WITH CARE

import * as FormDataEntryValue$WebAPI from "../../src/FetchAPI/FormDataEntryValue.js";

let formData = new FormData(document.forms.myForm);

let phoneEntry = formData.get("phone");

if (phoneEntry !== null) {
  let value = FormDataEntryValue$WebAPI.decode(phoneEntry);
  if (value.TAG === "String") {
    console.log(`Phone: ` + value._0);
  } else {
    console.log(`Unexpected file: ` + value._0.name);
  }
} else {
  console.log("No phone field");
}

let allImages = formData.getAll("images");

allImages.forEach(entry => {
  let value = FormDataEntryValue$WebAPI.decode(entry);
  if (value.TAG === "String") {
    console.log(`String value: ` + value._0);
    return;
  }
  console.log(`File: ` + value._0.name);
});

let fileEntry = new File([], "test.txt");

let entries = formData.entries();

entries.forEach(param => {
  let key = param[0];
  let s = FormDataEntryValue$WebAPI.decode(param[1]);
  if (s.TAG === "String") {
    console.log(key + `: ` + s._0);
    return;
  }
  console.log(key + `: [File] ` + s._0.name);
});

let stringEntry = "test value";

export {
  formData,
  phoneEntry,
  allImages,
  stringEntry,
  fileEntry,
  entries,
}
/* formData Not a pure module */
