// Generated by ReScript, PLEASE EDIT WITH CARE


let formData = new FormData(document.forms.myForm);

let phoneEntry = formData.get("phone");

if (phoneEntry !== null) {
  if (typeof phoneEntry === "string") {
    console.log(`Phone: ` + phoneEntry);
  } else {
    console.log(`Unexpected file: ` + phoneEntry.name);
  }
} else {
  console.log("No phone field");
}

let allImages = formData.getAll("images");

allImages.forEach(entry => {
  if (typeof entry === "string") {
    console.log(`String value: ` + entry);
    return;
  }
  console.log(`File: ` + entry.name);
});

let fileEntry = new File([], "test.txt");

let entries = formData.entries();

entries.forEach(param => {
  let value = param[1];
  let key = param[0];
  if (typeof value === "string") {
    console.log(key + `: ` + value);
    return;
  }
  console.log(key + `: [File] ` + value.name);
});

let stringEntry = "test value";

export {
  formData,
  phoneEntry,
  allImages,
  stringEntry,
  fileEntry,
  entries,
}
/* formData Not a pure module */
