// Generated by ReScript, PLEASE EDIT WITH CARE


let formData = new FormData(document.forms.myForm);

let phone = formData.get("phone");

let image = formData.get("image");

export {
  formData,
  phone,
  image,
}
/* formData Not a pure module */
