// Generated by ReScript, PLEASE EDIT WITH CARE


let response = new Response(null, {
  status: 204
});

let response1 = new Response("pong", {
  status: 200,
  headers: {
    "X-Fruit": "Peach"
  }
});

export {
  response,
  response1,
}
/* response Not a pure module */
