// Generated by ReScript, PLEASE EDIT WITH CARE


let params1 = new URLSearchParams("foo=1&bar=2");

Array.from(params1.keys()).forEach(prim => {
  console.log(prim);
});

let params2 = new URLSearchParams([
  [
    "foo",
    "1"
  ],
  [
    "bar",
    "b"
  ]
]);

Array.from(params2.values()).forEach(prim => {
  console.log(prim);
});

let params3 = new URLSearchParams({
  foo: "1",
  bar: "b"
});

Array.from(params3.entries()).forEach(param => {
  console.log(param[0], param[1]);
});

let paramStr = params3.toString();

export {
  params1,
  params2,
  params3,
  paramStr,
}
/* params1 Not a pure module */
