// Generated by ReScript, PLEASE EDIT WITH CARE


Notification.requestPermission().then(notificationPermission => {
  switch (notificationPermission) {
    case "default" :
      console.log("Permission default");
      return;
    case "denied" :
      console.log("Permission denied");
      return;
    case "granted" :
      console.log("Permission granted");
      return;
  }
});

/*  Not a pure module */
