// Generated by ReScript, PLEASE EDIT WITH CARE

import * as File$WebAPI from "../FileAPI/File.js";

function decode(t) {
  if (File$WebAPI.isInstanceOf(t)) {
    return {
      TAG: "File",
      _0: t
    };
  } else {
    return {
      TAG: "String",
      _0: t
    };
  }
}

export {
  decode,
}
/* File-WebAPI Not a pure module */
