// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Null from "rescript/lib/es6/Null.js";

for (let i = 0, i_finish = localStorage.length; i < i_finish; ++i) {
  console.log(Null.getOr(localStorage.key(i), "nothing"));
}

let item1 = Null.getOr(localStorage.getItem("foo"), "nothing");

localStorage.setItem("bar", "...");

localStorage.removeItem("bar");

localStorage.clear();

export {
  item1,
}
/*  Not a pure module */
