// Generated by ReScript, PLEASE EDIT WITH CARE


function isFileInstance(param) {
  return (param instanceof File);
}

function decode(t) {
  if (isFileInstance(t)) {
    return {
      TAG: "File",
      _0: t
    };
  } else {
    return {
      TAG: "String",
      _0: t
    };
  }
}

export {
  isFileInstance,
  decode,
}
/* No side effect */
