// Generated by ReScript, PLEASE EDIT WITH CARE

import * as UIEvent$WebAPI from "./UIEvent.js";

function Impl(T) {
  UIEvent$WebAPI.Impl({});
  return {};
}

UIEvent$WebAPI.Impl({});

export {
  Impl,
}
/*  Not a pure module */
