// Generated by ReScript, PLEASE EDIT WITH CARE

import * as UIEvent$UIEvents from "./UIEvent.js";

function Impl(T) {
  UIEvent$UIEvents.Impl({});
  return {};
}

UIEvent$UIEvents.Impl({});

export {
  Impl,
}
/*  Not a pure module */
