// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AudioNode$WebAPIWebAudio from "./AudioNode.js";

function Impl(T) {
  AudioNode$WebAPIWebAudio.Impl({});
  return {};
}

AudioNode$WebAPIWebAudio.Impl({});

export {
  Impl,
}
/*  Not a pure module */
