// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AudioNode$WebAudio from "./AudioNode.js";

function Impl(T) {
  AudioNode$WebAudio.Impl({});
  return {};
}

AudioNode$WebAudio.Impl({});

export {
  Impl,
}
/*  Not a pure module */
