// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EventTarget$Event from "@rescript-webapi/event/src/EventTarget.js";

function Impl(T) {
  EventTarget$Event.Impl({});
  return {};
}

export {
  Impl,
}
/* No side effect */
