// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Node$WebAPI from "./Node.js";

function Impl(T) {
  Node$WebAPI.Impl({});
  return {};
}

Node$WebAPI.Impl({});

export {
  Impl,
}
/*  Not a pure module */
