// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Node$WebAPI from "./Node.js";
import * as HTMLHeadingElement$WebAPI from "./HTMLHeadingElement.js";

Node$WebAPI.Impl({});

function querySelectorAsHeading(document, selector) {
  let element = document.querySelector(selector);
  if (element === null || !HTMLHeadingElement$WebAPI.isInstanceOf(element)) {
    return;
  } else {
    return element;
  }
}

function isInstanceOf(param) {
  return (param instanceof Document);
}

export {
  querySelectorAsHeading,
  isInstanceOf,
}
/*  Not a pure module */
