// Generated by ReScript, PLEASE EDIT WITH CARE

import * as QuerySelector$WebAPI from "./QuerySelector.js";

let include = QuerySelector$WebAPI.Impl({});

let querySelector_htmlCanvasElement = include.querySelector_htmlCanvasElement;

export {
  querySelector_htmlCanvasElement,
}
/* include Not a pure module */
