// Generated by ReScript, PLEASE EDIT WITH CARE

import * as QuerySelector$WebAPI from "./QuerySelector.js";

let include = QuerySelector$WebAPI.Impl({});

let safeQuerySelector = include.safeQuerySelector;

let querySelector_htmlCanvasElement = include.querySelector_htmlCanvasElement;

let querySelector_htmlDivElement = include.querySelector_htmlDivElement;

export {
  safeQuerySelector,
  querySelector_htmlCanvasElement,
  querySelector_htmlDivElement,
}
/* include Not a pure module */
