// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Node$WebAPI from "./Node.js";

function Impl(T) {
  Node$WebAPI.Impl({});
  return {};
}

Node$WebAPI.Impl({});

function isInstanceOf(param) {
  return (param instanceof Element);
}

export {
  Impl,
  isInstanceOf,
}
/*  Not a pure module */
