// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Node$WebApi from "./Node.js";

function Impl(T) {
  Node$WebApi.Impl({});
  return {};
}

Node$WebApi.Impl({});

export {
  Impl,
}
/*  Not a pure module */
