// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CanvasPattern$WebAPI from "../CanvasAPI/CanvasPattern.js";
import * as CanvasGradient$WebAPI from "../CanvasAPI/CanvasGradient.js";

function decode(t) {
  if (CanvasGradient$WebAPI.isInstanceOf(t)) {
    return {
      TAG: "CanvasGradient",
      _0: t
    };
  } else if (CanvasPattern$WebAPI.isInstanceOf(t)) {
    return {
      TAG: "CanvasPattern",
      _0: t
    };
  } else {
    return {
      TAG: "String",
      _0: t
    };
  }
}

export {
  decode,
}
/* No side effect */
