// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Element$WebApi from "./Element.js";

function Impl(T) {
  Element$WebApi.Impl({});
  return {};
}

Element$WebApi.Impl({});

export {
  Impl,
}
/*  Not a pure module */
