// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Element$WebAPI from "./Element.js";

function Impl(T) {
  Element$WebAPI.Impl({});
  return {};
}

export {
  Impl,
}
/* Element-WebAPI Not a pure module */
