// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Element$WebApi from "./Element.js";

function Impl(T) {
  Element$WebApi.Impl({});
  return {};
}

export {
  Impl,
}
/* Element-WebApi Not a pure module */
