// Generated by ReScript, PLEASE EDIT WITH CARE

import * as QuerySelector$WebAPI from "./QuerySelector.js";

let include = QuerySelector$WebAPI.Impl({});

let safeQuerySelector = include.safeQuerySelector;

let querySelector_htmlAnchorElement = include.querySelector_htmlAnchorElement;

let querySelector_htmlAreaElement = include.querySelector_htmlAreaElement;

let querySelector_htmlAudioElement = include.querySelector_htmlAudioElement;

let querySelector_htmlBaseElement = include.querySelector_htmlBaseElement;

let querySelector_htmlBodyElement = include.querySelector_htmlBodyElement;

let querySelector_htmlBRElement = include.querySelector_htmlBRElement;

let querySelector_htmlButtonElement = include.querySelector_htmlButtonElement;

let querySelector_htmlCanvasElement = include.querySelector_htmlCanvasElement;

let querySelector_htmlDataElement = include.querySelector_htmlDataElement;

let querySelector_htmlDataListElement = include.querySelector_htmlDataListElement;

let querySelector_htmlDetailsElement = include.querySelector_htmlDetailsElement;

let querySelector_htmlDialogElement = include.querySelector_htmlDialogElement;

let querySelector_htmlDivElement = include.querySelector_htmlDivElement;

let querySelector_htmlDListElement = include.querySelector_htmlDListElement;

let querySelector_htmlEmbedElement = include.querySelector_htmlEmbedElement;

let querySelector_htmlFieldSetElement = include.querySelector_htmlFieldSetElement;

let querySelector_htmlFormElement = include.querySelector_htmlFormElement;

let querySelector_htmlHRElement = include.querySelector_htmlHRElement;

let querySelector_htmlHeadElement = include.querySelector_htmlHeadElement;

let querySelector_htmlHeadingElement = include.querySelector_htmlHeadingElement;

let querySelector_htmlHtmlElement = include.querySelector_htmlHtmlElement;

let querySelector_htmlIFrameElement = include.querySelector_htmlIFrameElement;

let querySelector_htmlImageElement = include.querySelector_htmlImageElement;

let querySelector_htmlInputElement = include.querySelector_htmlInputElement;

let querySelector_htmlLabelElement = include.querySelector_htmlLabelElement;

let querySelector_htmlLegendElement = include.querySelector_htmlLegendElement;

let querySelector_htmlLIElement = include.querySelector_htmlLIElement;

let querySelector_htmlLinkElement = include.querySelector_htmlLinkElement;

let querySelector_htmlMapElement = include.querySelector_htmlMapElement;

let querySelector_htmlMediaElement = include.querySelector_htmlMediaElement;

let querySelector_htmlMenuElement = include.querySelector_htmlMenuElement;

let querySelector_htmlMetaElement = include.querySelector_htmlMetaElement;

let querySelector_htmlMeterElement = include.querySelector_htmlMeterElement;

let querySelector_htmlModElement = include.querySelector_htmlModElement;

let querySelector_htmlObjectElement = include.querySelector_htmlObjectElement;

let querySelector_htmlOListElement = include.querySelector_htmlOListElement;

let querySelector_htmlOptGroupElement = include.querySelector_htmlOptGroupElement;

let querySelector_htmlOptionElement = include.querySelector_htmlOptionElement;

let querySelector_htmlOutputElement = include.querySelector_htmlOutputElement;

let querySelector_htmlParagraphElement = include.querySelector_htmlParagraphElement;

let querySelector_htmlPictureElement = include.querySelector_htmlPictureElement;

let querySelector_htmlPreElement = include.querySelector_htmlPreElement;

let querySelector_htmlProgressElement = include.querySelector_htmlProgressElement;

let querySelector_htmlQuoteElement = include.querySelector_htmlQuoteElement;

let querySelector_htmlScriptElement = include.querySelector_htmlScriptElement;

let querySelector_htmlSelectElement = include.querySelector_htmlSelectElement;

let querySelector_htmlSlotElement = include.querySelector_htmlSlotElement;

let querySelector_htmlSourceElement = include.querySelector_htmlSourceElement;

let querySelector_htmlSpanElement = include.querySelector_htmlSpanElement;

let querySelector_htmlStyleElement = include.querySelector_htmlStyleElement;

let querySelector_htmlTableCaptionElement = include.querySelector_htmlTableCaptionElement;

let querySelector_htmlTableCellElement = include.querySelector_htmlTableCellElement;

let querySelector_htmlTableColElement = include.querySelector_htmlTableColElement;

let querySelector_htmlTableElement = include.querySelector_htmlTableElement;

let querySelector_htmlTableRowElement = include.querySelector_htmlTableRowElement;

let querySelector_htmlTableSectionElement = include.querySelector_htmlTableSectionElement;

let querySelector_htmlTemplateElement = include.querySelector_htmlTemplateElement;

let querySelector_htmlTextAreaElement = include.querySelector_htmlTextAreaElement;

let querySelector_htmlTimeElement = include.querySelector_htmlTimeElement;

let querySelector_htmlTitleElement = include.querySelector_htmlTitleElement;

let querySelector_htmlTrackElement = include.querySelector_htmlTrackElement;

let querySelector_htmlUListElement = include.querySelector_htmlUListElement;

let querySelector_htmlUnknownElement = include.querySelector_htmlUnknownElement;

let querySelector_htmlVideoElement = include.querySelector_htmlVideoElement;

export {
  safeQuerySelector,
  querySelector_htmlAnchorElement,
  querySelector_htmlAreaElement,
  querySelector_htmlAudioElement,
  querySelector_htmlBaseElement,
  querySelector_htmlBodyElement,
  querySelector_htmlBRElement,
  querySelector_htmlButtonElement,
  querySelector_htmlCanvasElement,
  querySelector_htmlDataElement,
  querySelector_htmlDataListElement,
  querySelector_htmlDetailsElement,
  querySelector_htmlDialogElement,
  querySelector_htmlDivElement,
  querySelector_htmlDListElement,
  querySelector_htmlEmbedElement,
  querySelector_htmlFieldSetElement,
  querySelector_htmlFormElement,
  querySelector_htmlHRElement,
  querySelector_htmlHeadElement,
  querySelector_htmlHeadingElement,
  querySelector_htmlHtmlElement,
  querySelector_htmlIFrameElement,
  querySelector_htmlImageElement,
  querySelector_htmlInputElement,
  querySelector_htmlLabelElement,
  querySelector_htmlLegendElement,
  querySelector_htmlLIElement,
  querySelector_htmlLinkElement,
  querySelector_htmlMapElement,
  querySelector_htmlMediaElement,
  querySelector_htmlMenuElement,
  querySelector_htmlMetaElement,
  querySelector_htmlMeterElement,
  querySelector_htmlModElement,
  querySelector_htmlObjectElement,
  querySelector_htmlOListElement,
  querySelector_htmlOptGroupElement,
  querySelector_htmlOptionElement,
  querySelector_htmlOutputElement,
  querySelector_htmlParagraphElement,
  querySelector_htmlPictureElement,
  querySelector_htmlPreElement,
  querySelector_htmlProgressElement,
  querySelector_htmlQuoteElement,
  querySelector_htmlScriptElement,
  querySelector_htmlSelectElement,
  querySelector_htmlSlotElement,
  querySelector_htmlSourceElement,
  querySelector_htmlSpanElement,
  querySelector_htmlStyleElement,
  querySelector_htmlTableCaptionElement,
  querySelector_htmlTableCellElement,
  querySelector_htmlTableColElement,
  querySelector_htmlTableElement,
  querySelector_htmlTableRowElement,
  querySelector_htmlTableSectionElement,
  querySelector_htmlTemplateElement,
  querySelector_htmlTextAreaElement,
  querySelector_htmlTimeElement,
  querySelector_htmlTitleElement,
  querySelector_htmlTrackElement,
  querySelector_htmlUListElement,
  querySelector_htmlUnknownElement,
  querySelector_htmlVideoElement,
}
/* include Not a pure module */
