// Generated by ReScript, PLEASE EDIT WITH CARE

import * as HTMLElement$WebAPI from "./HTMLElement.js";

function Impl(T) {
  HTMLElement$WebAPI.Impl({});
  return {};
}

HTMLElement$WebAPI.Impl({});

export {
  Impl,
}
/*  Not a pure module */
