// Generated by ReScript, PLEASE EDIT WITH CARE

import * as HTMLElement$WebApi from "./HTMLElement.js";

function Impl(T) {
  HTMLElement$WebApi.Impl({});
  return {};
}

HTMLElement$WebApi.Impl({});

export {
  Impl,
}
/*  Not a pure module */
