// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EventTarget$WebAPI from "../EventAPI/EventTarget.js";

function Impl(T) {
  EventTarget$WebAPI.Impl({});
  return {};
}

EventTarget$WebAPI.Impl({});

export {
  Impl,
}
/*  Not a pure module */
