// Generated by ReScript, PLEASE EDIT WITH CARE

import * as HTMLCanvasElement$WebAPI from "./HTMLCanvasElement.js";

function Impl(T) {
  let querySelector_htmlCanvasElement = (t, selector) => {
    let e = t.querySelector(selector);
    if (e === null || !HTMLCanvasElement$WebAPI.isInstanceOf(e)) {
      return;
    } else {
      return e;
    }
  };
  return {
    querySelector_htmlCanvasElement: querySelector_htmlCanvasElement
  };
}

export {
  Impl,
}
/* No side effect */
