// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";

function isInstanceOfHTMLAnchorElement(param) {
  return (param instanceof HTMLAnchorElement);
}

function isInstanceOfHTMLAreaElement(param) {
  return (param instanceof HTMLAreaElement);
}

function isInstanceOfHTMLAudioElement(param) {
  return (param instanceof HTMLAudioElement);
}

function isInstanceOfHTMLBaseElement(param) {
  return (param instanceof HTMLBaseElement);
}

function isInstanceOfHTMLBodyElement(param) {
  return (param instanceof HTMLBodyElement);
}

function isInstanceOfHTMLBRElement(param) {
  return (param instanceof HTMLBRElement);
}

function isInstanceOfHTMLButtonElement(param) {
  return (param instanceof HTMLButtonElement);
}

function isInstanceOfHTMLCanvasElement(param) {
  return (param instanceof HTMLCanvasElement);
}

function isInstanceOfHTMLDataElement(param) {
  return (param instanceof HTMLDataElement);
}

function isInstanceOfHTMLDataListElement(param) {
  return (param instanceof HTMLDataListElement);
}

function isInstanceOfHTMLDetailsElement(param) {
  return (param instanceof HTMLDetailsElement);
}

function isInstanceOfHTMLDialogElement(param) {
  return (param instanceof HTMLDialogElement);
}

function isInstanceOfHTMLDivElement(param) {
  return (param instanceof HTMLDivElement);
}

function isInstanceOfHTMLDListElement(param) {
  return (param instanceof HTMLDListElement);
}

function isInstanceOfHTMLEmbedElement(param) {
  return (param instanceof HTMLEmbedElement);
}

function isInstanceOfHTMLFieldSetElement(param) {
  return (param instanceof HTMLFieldSetElement);
}

function isInstanceOfHTMLFormElement(param) {
  return (param instanceof HTMLFormElement);
}

function isInstanceOfHTMLHRElement(param) {
  return (param instanceof HTMLHRElement);
}

function isInstanceOfHTMLHeadElement(param) {
  return (param instanceof HTMLHeadElement);
}

function isInstanceOfHTMLHeadingElement(param) {
  return (param instanceof HTMLHeadingElement);
}

function isInstanceOfHTMLHtmlElement(param) {
  return (param instanceof HTMLHtmlElement);
}

function isInstanceOfHTMLIFrameElement(param) {
  return (param instanceof HTMLIFrameElement);
}

function isInstanceOfHTMLImageElement(param) {
  return (param instanceof HTMLImageElement);
}

function isInstanceOfHTMLInputElement(param) {
  return (param instanceof HTMLInputElement);
}

function isInstanceOfHTMLLabelElement(param) {
  return (param instanceof HTMLLabelElement);
}

function isInstanceOfHTMLLegendElement(param) {
  return (param instanceof HTMLLegendElement);
}

function isInstanceOfHTMLLIElement(param) {
  return (param instanceof HTMLLIElement);
}

function isInstanceOfHTMLLinkElement(param) {
  return (param instanceof HTMLLinkElement);
}

function isInstanceOfHTMLMapElement(param) {
  return (param instanceof HTMLMapElement);
}

function isInstanceOfHTMLMediaElement(param) {
  return (param instanceof HTMLMediaElement);
}

function isInstanceOfHTMLMenuElement(param) {
  return (param instanceof HTMLMenuElement);
}

function isInstanceOfHTMLMetaElement(param) {
  return (param instanceof HTMLMetaElement);
}

function isInstanceOfHTMLMeterElement(param) {
  return (param instanceof HTMLMeterElement);
}

function isInstanceOfHTMLModElement(param) {
  return (param instanceof HTMLModElement);
}

function isInstanceOfHTMLObjectElement(param) {
  return (param instanceof HTMLObjectElement);
}

function isInstanceOfHTMLOListElement(param) {
  return (param instanceof HTMLOListElement);
}

function isInstanceOfHTMLOptGroupElement(param) {
  return (param instanceof HTMLOptGroupElement);
}

function isInstanceOfHTMLOptionElement(param) {
  return (param instanceof HTMLOptionElement);
}

function isInstanceOfHTMLOutputElement(param) {
  return (param instanceof HTMLOutputElement);
}

function isInstanceOfHTMLParagraphElement(param) {
  return (param instanceof HTMLParagraphElement);
}

function isInstanceOfHTMLPictureElement(param) {
  return (param instanceof HTMLPictureElement);
}

function isInstanceOfHTMLPreElement(param) {
  return (param instanceof HTMLPreElement);
}

function isInstanceOfHTMLProgressElement(param) {
  return (param instanceof HTMLProgressElement);
}

function isInstanceOfHTMLQuoteElement(param) {
  return (param instanceof HTMLQuoteElement);
}

function isInstanceOfHTMLScriptElement(param) {
  return (param instanceof HTMLScriptElement);
}

function isInstanceOfHTMLSelectElement(param) {
  return (param instanceof HTMLSelectElement);
}

function isInstanceOfHTMLSlotElement(param) {
  return (param instanceof HTMLSlotElement);
}

function isInstanceOfHTMLSourceElement(param) {
  return (param instanceof HTMLSourceElement);
}

function isInstanceOfHTMLSpanElement(param) {
  return (param instanceof HTMLSpanElement);
}

function isInstanceOfHTMLStyleElement(param) {
  return (param instanceof HTMLStyleElement);
}

function isInstanceOfHTMLTableCaptionElement(param) {
  return (param instanceof HTMLTableCaptionElement);
}

function isInstanceOfHTMLTableCellElement(param) {
  return (param instanceof HTMLTableCellElement);
}

function isInstanceOfHTMLTableColElement(param) {
  return (param instanceof HTMLTableColElement);
}

function isInstanceOfHTMLTableElement(param) {
  return (param instanceof HTMLTableElement);
}

function isInstanceOfHTMLTableRowElement(param) {
  return (param instanceof HTMLTableRowElement);
}

function isInstanceOfHTMLTableSectionElement(param) {
  return (param instanceof HTMLTableSectionElement);
}

function isInstanceOfHTMLTemplateElement(param) {
  return (param instanceof HTMLTemplateElement);
}

function isInstanceOfHTMLTextAreaElement(param) {
  return (param instanceof HTMLTextAreaElement);
}

function isInstanceOfHTMLTimeElement(param) {
  return (param instanceof HTMLTimeElement);
}

function isInstanceOfHTMLTitleElement(param) {
  return (param instanceof HTMLTitleElement);
}

function isInstanceOfHTMLTrackElement(param) {
  return (param instanceof HTMLTrackElement);
}

function isInstanceOfHTMLUListElement(param) {
  return (param instanceof HTMLUListElement);
}

function isInstanceOfHTMLUnknownElement(param) {
  return (param instanceof HTMLUnknownElement);
}

function isInstanceOfHTMLVideoElement(param) {
  return (param instanceof HTMLVideoElement);
}

function Impl(T) {
  let safeQuerySelector = (predicate, t, selector) => {
    let e = t.querySelector(selector);
    if (e === null || !predicate(t)) {
      return;
    } else {
      return Primitive_option.some(e);
    }
  };
  let querySelector_htmlAnchorElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLAnchorElement, t, selector);
  let querySelector_htmlAreaElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLAreaElement, t, selector);
  let querySelector_htmlAudioElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLAudioElement, t, selector);
  let querySelector_htmlBaseElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLBaseElement, t, selector);
  let querySelector_htmlBodyElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLBodyElement, t, selector);
  let querySelector_htmlBRElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLBRElement, t, selector);
  let querySelector_htmlButtonElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLButtonElement, t, selector);
  let querySelector_htmlCanvasElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLCanvasElement, t, selector);
  let querySelector_htmlDataElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLDataElement, t, selector);
  let querySelector_htmlDataListElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLDataListElement, t, selector);
  let querySelector_htmlDetailsElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLDetailsElement, t, selector);
  let querySelector_htmlDialogElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLDialogElement, t, selector);
  let querySelector_htmlDivElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLDivElement, t, selector);
  let querySelector_htmlDListElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLDListElement, t, selector);
  let querySelector_htmlEmbedElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLEmbedElement, t, selector);
  let querySelector_htmlFieldSetElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLFieldSetElement, t, selector);
  let querySelector_htmlFormElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLFormElement, t, selector);
  let querySelector_htmlHRElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLHRElement, t, selector);
  let querySelector_htmlHeadElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLHeadElement, t, selector);
  let querySelector_htmlHeadingElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLHeadingElement, t, selector);
  let querySelector_htmlHtmlElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLHtmlElement, t, selector);
  let querySelector_htmlIFrameElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLIFrameElement, t, selector);
  let querySelector_htmlImageElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLImageElement, t, selector);
  let querySelector_htmlInputElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLInputElement, t, selector);
  let querySelector_htmlLabelElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLLabelElement, t, selector);
  let querySelector_htmlLegendElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLLegendElement, t, selector);
  let querySelector_htmlLIElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLLIElement, t, selector);
  let querySelector_htmlLinkElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLLinkElement, t, selector);
  let querySelector_htmlMapElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLMapElement, t, selector);
  let querySelector_htmlMediaElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLMediaElement, t, selector);
  let querySelector_htmlMenuElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLMenuElement, t, selector);
  let querySelector_htmlMetaElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLMetaElement, t, selector);
  let querySelector_htmlMeterElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLMeterElement, t, selector);
  let querySelector_htmlModElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLModElement, t, selector);
  let querySelector_htmlObjectElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLObjectElement, t, selector);
  let querySelector_htmlOListElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLOListElement, t, selector);
  let querySelector_htmlOptGroupElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLOptGroupElement, t, selector);
  let querySelector_htmlOptionElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLOptionElement, t, selector);
  let querySelector_htmlOutputElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLOutputElement, t, selector);
  let querySelector_htmlParagraphElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLParagraphElement, t, selector);
  let querySelector_htmlPictureElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLPictureElement, t, selector);
  let querySelector_htmlPreElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLPreElement, t, selector);
  let querySelector_htmlProgressElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLProgressElement, t, selector);
  let querySelector_htmlQuoteElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLQuoteElement, t, selector);
  let querySelector_htmlScriptElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLScriptElement, t, selector);
  let querySelector_htmlSelectElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLSelectElement, t, selector);
  let querySelector_htmlSlotElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLSlotElement, t, selector);
  let querySelector_htmlSourceElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLSourceElement, t, selector);
  let querySelector_htmlSpanElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLSpanElement, t, selector);
  let querySelector_htmlStyleElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLStyleElement, t, selector);
  let querySelector_htmlTableCaptionElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLTableCaptionElement, t, selector);
  let querySelector_htmlTableCellElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLTableCellElement, t, selector);
  let querySelector_htmlTableColElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLTableColElement, t, selector);
  let querySelector_htmlTableElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLTableElement, t, selector);
  let querySelector_htmlTableRowElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLTableRowElement, t, selector);
  let querySelector_htmlTableSectionElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLTableSectionElement, t, selector);
  let querySelector_htmlTemplateElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLTemplateElement, t, selector);
  let querySelector_htmlTextAreaElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLTextAreaElement, t, selector);
  let querySelector_htmlTimeElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLTimeElement, t, selector);
  let querySelector_htmlTitleElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLTitleElement, t, selector);
  let querySelector_htmlTrackElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLTrackElement, t, selector);
  let querySelector_htmlUListElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLUListElement, t, selector);
  let querySelector_htmlUnknownElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLUnknownElement, t, selector);
  let querySelector_htmlVideoElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLVideoElement, t, selector);
  return {
    safeQuerySelector: safeQuerySelector,
    querySelector_htmlAnchorElement: querySelector_htmlAnchorElement,
    querySelector_htmlAreaElement: querySelector_htmlAreaElement,
    querySelector_htmlAudioElement: querySelector_htmlAudioElement,
    querySelector_htmlBaseElement: querySelector_htmlBaseElement,
    querySelector_htmlBodyElement: querySelector_htmlBodyElement,
    querySelector_htmlBRElement: querySelector_htmlBRElement,
    querySelector_htmlButtonElement: querySelector_htmlButtonElement,
    querySelector_htmlCanvasElement: querySelector_htmlCanvasElement,
    querySelector_htmlDataElement: querySelector_htmlDataElement,
    querySelector_htmlDataListElement: querySelector_htmlDataListElement,
    querySelector_htmlDetailsElement: querySelector_htmlDetailsElement,
    querySelector_htmlDialogElement: querySelector_htmlDialogElement,
    querySelector_htmlDivElement: querySelector_htmlDivElement,
    querySelector_htmlDListElement: querySelector_htmlDListElement,
    querySelector_htmlEmbedElement: querySelector_htmlEmbedElement,
    querySelector_htmlFieldSetElement: querySelector_htmlFieldSetElement,
    querySelector_htmlFormElement: querySelector_htmlFormElement,
    querySelector_htmlHRElement: querySelector_htmlHRElement,
    querySelector_htmlHeadElement: querySelector_htmlHeadElement,
    querySelector_htmlHeadingElement: querySelector_htmlHeadingElement,
    querySelector_htmlHtmlElement: querySelector_htmlHtmlElement,
    querySelector_htmlIFrameElement: querySelector_htmlIFrameElement,
    querySelector_htmlImageElement: querySelector_htmlImageElement,
    querySelector_htmlInputElement: querySelector_htmlInputElement,
    querySelector_htmlLabelElement: querySelector_htmlLabelElement,
    querySelector_htmlLegendElement: querySelector_htmlLegendElement,
    querySelector_htmlLIElement: querySelector_htmlLIElement,
    querySelector_htmlLinkElement: querySelector_htmlLinkElement,
    querySelector_htmlMapElement: querySelector_htmlMapElement,
    querySelector_htmlMediaElement: querySelector_htmlMediaElement,
    querySelector_htmlMenuElement: querySelector_htmlMenuElement,
    querySelector_htmlMetaElement: querySelector_htmlMetaElement,
    querySelector_htmlMeterElement: querySelector_htmlMeterElement,
    querySelector_htmlModElement: querySelector_htmlModElement,
    querySelector_htmlObjectElement: querySelector_htmlObjectElement,
    querySelector_htmlOListElement: querySelector_htmlOListElement,
    querySelector_htmlOptGroupElement: querySelector_htmlOptGroupElement,
    querySelector_htmlOptionElement: querySelector_htmlOptionElement,
    querySelector_htmlOutputElement: querySelector_htmlOutputElement,
    querySelector_htmlParagraphElement: querySelector_htmlParagraphElement,
    querySelector_htmlPictureElement: querySelector_htmlPictureElement,
    querySelector_htmlPreElement: querySelector_htmlPreElement,
    querySelector_htmlProgressElement: querySelector_htmlProgressElement,
    querySelector_htmlQuoteElement: querySelector_htmlQuoteElement,
    querySelector_htmlScriptElement: querySelector_htmlScriptElement,
    querySelector_htmlSelectElement: querySelector_htmlSelectElement,
    querySelector_htmlSlotElement: querySelector_htmlSlotElement,
    querySelector_htmlSourceElement: querySelector_htmlSourceElement,
    querySelector_htmlSpanElement: querySelector_htmlSpanElement,
    querySelector_htmlStyleElement: querySelector_htmlStyleElement,
    querySelector_htmlTableCaptionElement: querySelector_htmlTableCaptionElement,
    querySelector_htmlTableCellElement: querySelector_htmlTableCellElement,
    querySelector_htmlTableColElement: querySelector_htmlTableColElement,
    querySelector_htmlTableElement: querySelector_htmlTableElement,
    querySelector_htmlTableRowElement: querySelector_htmlTableRowElement,
    querySelector_htmlTableSectionElement: querySelector_htmlTableSectionElement,
    querySelector_htmlTemplateElement: querySelector_htmlTemplateElement,
    querySelector_htmlTextAreaElement: querySelector_htmlTextAreaElement,
    querySelector_htmlTimeElement: querySelector_htmlTimeElement,
    querySelector_htmlTitleElement: querySelector_htmlTitleElement,
    querySelector_htmlTrackElement: querySelector_htmlTrackElement,
    querySelector_htmlUListElement: querySelector_htmlUListElement,
    querySelector_htmlUnknownElement: querySelector_htmlUnknownElement,
    querySelector_htmlVideoElement: querySelector_htmlVideoElement
  };
}

export {
  isInstanceOfHTMLAnchorElement,
  isInstanceOfHTMLAreaElement,
  isInstanceOfHTMLAudioElement,
  isInstanceOfHTMLBaseElement,
  isInstanceOfHTMLBodyElement,
  isInstanceOfHTMLBRElement,
  isInstanceOfHTMLButtonElement,
  isInstanceOfHTMLCanvasElement,
  isInstanceOfHTMLDataElement,
  isInstanceOfHTMLDataListElement,
  isInstanceOfHTMLDetailsElement,
  isInstanceOfHTMLDialogElement,
  isInstanceOfHTMLDivElement,
  isInstanceOfHTMLDListElement,
  isInstanceOfHTMLEmbedElement,
  isInstanceOfHTMLFieldSetElement,
  isInstanceOfHTMLFormElement,
  isInstanceOfHTMLHRElement,
  isInstanceOfHTMLHeadElement,
  isInstanceOfHTMLHeadingElement,
  isInstanceOfHTMLHtmlElement,
  isInstanceOfHTMLIFrameElement,
  isInstanceOfHTMLImageElement,
  isInstanceOfHTMLInputElement,
  isInstanceOfHTMLLabelElement,
  isInstanceOfHTMLLegendElement,
  isInstanceOfHTMLLIElement,
  isInstanceOfHTMLLinkElement,
  isInstanceOfHTMLMapElement,
  isInstanceOfHTMLMediaElement,
  isInstanceOfHTMLMenuElement,
  isInstanceOfHTMLMetaElement,
  isInstanceOfHTMLMeterElement,
  isInstanceOfHTMLModElement,
  isInstanceOfHTMLObjectElement,
  isInstanceOfHTMLOListElement,
  isInstanceOfHTMLOptGroupElement,
  isInstanceOfHTMLOptionElement,
  isInstanceOfHTMLOutputElement,
  isInstanceOfHTMLParagraphElement,
  isInstanceOfHTMLPictureElement,
  isInstanceOfHTMLPreElement,
  isInstanceOfHTMLProgressElement,
  isInstanceOfHTMLQuoteElement,
  isInstanceOfHTMLScriptElement,
  isInstanceOfHTMLSelectElement,
  isInstanceOfHTMLSlotElement,
  isInstanceOfHTMLSourceElement,
  isInstanceOfHTMLSpanElement,
  isInstanceOfHTMLStyleElement,
  isInstanceOfHTMLTableCaptionElement,
  isInstanceOfHTMLTableCellElement,
  isInstanceOfHTMLTableColElement,
  isInstanceOfHTMLTableElement,
  isInstanceOfHTMLTableRowElement,
  isInstanceOfHTMLTableSectionElement,
  isInstanceOfHTMLTemplateElement,
  isInstanceOfHTMLTextAreaElement,
  isInstanceOfHTMLTimeElement,
  isInstanceOfHTMLTitleElement,
  isInstanceOfHTMLTrackElement,
  isInstanceOfHTMLUListElement,
  isInstanceOfHTMLUnknownElement,
  isInstanceOfHTMLVideoElement,
  Impl,
}
/* No side effect */
