// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";

function isInstanceOfHTMLCanvasElement(param) {
  return (param instanceof HTMLCanvasElement);
}

function isInstanceOfHTMLDivElement(param) {
  return (param instanceof HTMLDivElement);
}

function Impl(T) {
  let safeQuerySelector = (predicate, t, selector) => {
    let e = t.querySelector(selector);
    if (e === null || !predicate(t)) {
      return;
    } else {
      return Primitive_option.some(e);
    }
  };
  let querySelector_htmlCanvasElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLCanvasElement, t, selector);
  let querySelector_htmlDivElement = (t, selector) => safeQuerySelector(isInstanceOfHTMLDivElement, t, selector);
  return {
    safeQuerySelector: safeQuerySelector,
    querySelector_htmlCanvasElement: querySelector_htmlCanvasElement,
    querySelector_htmlDivElement: querySelector_htmlDivElement
  };
}

export {
  isInstanceOfHTMLCanvasElement,
  isInstanceOfHTMLDivElement,
  Impl,
}
/* No side effect */
