// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Node$DOM from "./Node.js";

function Impl(T) {
  Node$DOM.Impl({});
  return {};
}

Node$DOM.Impl({});

export {
  Impl,
}
/*  Not a pure module */
