// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Node$DOM from "./Node.js";

Node$DOM.Impl({});

function isInstanceOf(param) {
  return (param instanceof Document);
}

export {
  isInstanceOf,
}
/*  Not a pure module */
