// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Node$DOM from "./Node.js";

function Impl(T) {
  Node$DOM.Impl({});
  return {};
}

Node$DOM.Impl({});

function isInstanceOf(param) {
  return (param instanceof Element);
}

export {
  Impl,
  isInstanceOf,
}
/*  Not a pure module */
