// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Element$DOM from "./Element.js";

function Impl(T) {
  Element$DOM.Impl({});
  return {};
}

Element$DOM.Impl({});

export {
  Impl,
}
/*  Not a pure module */
