// Generated by ReScript, PLEASE EDIT WITH CARE

import * as HTMLElement$DOM from "./HTMLElement.js";

function Impl(T) {
  HTMLElement$DOM.Impl({});
  return {};
}

HTMLElement$DOM.Impl({});

export {
  Impl,
}
/*  Not a pure module */
