// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Element$WebAPI from "../DOM/Element.js";
import * as Document$WebAPI from "../DOM/Document.js";

function decode(t) {
  if (Element$WebAPI.isInstanceOf(t)) {
    return {
      TAG: "Element",
      _0: t
    };
  } else if (Document$WebAPI.isInstanceOf(t)) {
    return {
      TAG: "Document",
      _0: t
    };
  } else {
    return "Null";
  }
}

export {
  decode,
}
/* Element-WebAPI Not a pure module */
