// Generated by ReScript, PLEASE EDIT WITH CARE


let ctx = new AudioContext();

let destinationNode = ctx.destination;

let osc = new OscillatorNode(ctx, {
  type: "sine",
  frequency: 440.0
});

let gain = new GainNode(ctx, {
  gain: 0.3
});

gain.connect(destinationNode);

osc.connect(gain);

osc.start();

let context = ctx;

export {
  ctx,
  destinationNode,
  context,
  osc,
  gain,
}
/* ctx Not a pure module */
