// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CanvasPattern$WebAPICanvas from "./CanvasPattern.js";
import * as CanvasGradient$WebAPICanvas from "./CanvasGradient.js";

function decode(t) {
  if (CanvasGradient$WebAPICanvas.isInstanceOf(t)) {
    return {
      TAG: "CanvasGradient",
      _0: t
    };
  } else if (CanvasPattern$WebAPICanvas.isInstanceOf(t)) {
    return {
      TAG: "CanvasPattern",
      _0: t
    };
  } else {
    return {
      TAG: "String",
      _0: t
    };
  }
}

export {
  decode,
}
/* No side effect */
