// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Node$WebAPIDom from "./Node.js";

Node$WebAPIDom.Impl({});

function isInstanceOf(param) {
  return (param instanceof Document);
}

export {
  isInstanceOf,
}
/*  Not a pure module */
