// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Node$WebAPIDom from "./Node.js";

function Impl(T) {
  Node$WebAPIDom.Impl({});
  return {};
}

Node$WebAPIDom.Impl({});

export {
  Impl,
}
/*  Not a pure module */
