// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Node$WebAPIDom from "./Node.js";

function Impl(T) {
  Node$WebAPIDom.Impl({});
  return {};
}

Node$WebAPIDom.Impl({});

function isInstanceOf(param) {
  return (param instanceof Element);
}

export {
  Impl,
  isInstanceOf,
}
/*  Not a pure module */
