// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Element$WebAPIDom from "./Element.js";

function Impl(T) {
  Element$WebAPIDom.Impl({});
  return {};
}

Element$WebAPIDom.Impl({});

export {
  Impl,
}
/*  Not a pure module */
