// Generated by ReScript, PLEASE EDIT WITH CARE

import * as HTMLElement$WebAPIDom from "./HTMLElement.js";

function Impl(T) {
  HTMLElement$WebAPIDom.Impl({});
  return {};
}

HTMLElement$WebAPIDom.Impl({});

export {
  Impl,
}
/*  Not a pure module */
