// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Element$WebAPIDom from "./Element.js";
import * as Document$WebAPIDom from "./Document.js";

function decode(t) {
  if (Element$WebAPIDom.isInstanceOf(t)) {
    return {
      TAG: "Element",
      _0: t
    };
  } else if (Document$WebAPIDom.isInstanceOf(t)) {
    return {
      TAG: "Document",
      _0: t
    };
  } else {
    return "Null";
  }
}

export {
  decode,
}
/* Element-WebAPIDom Not a pure module */
