// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Blob$WebAPIFile from "./Blob.js";

Blob$WebAPIFile.Impl({});

function isInstanceOf(param) {
  return (param instanceof File);
}

export {
  isInstanceOf,
}
/*  Not a pure module */
