// Generated by ReScript, PLEASE EDIT WITH CARE


let value = myElement.getAttribute("foo");

if (value === null) {
  console.log("nothing");
} else {
  console.log(value);
}

/* value Not a pure module */
