// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

Stdlib_Option.forEach(Primitive_option.fromNull(document.querySelector("form")), form => {
  form.scrollIntoView({
    behavior: "smooth"
  });
});

/*  Not a pure module */
