/**
The results generated by evaluating an XPath expression within the context of a given node.
[See XPathResult on MDN](https://developer.mozilla.org/docs/Web/API/XPathResult)
*/
type t = private {
  /**
[Read more on MDN](https://developer.mozilla.org/docs/Web/API/XPathResult/resultType)
*/
  resultType: int,
  /**
[Read more on MDN](https://developer.mozilla.org/docs/Web/API/XPathResult/numberValue)
*/
  numberValue: float,
  /**
[Read more on MDN](https://developer.mozilla.org/docs/Web/API/XPathResult/stringValue)
*/
  stringValue: string,
  /**
[Read more on MDN](https://developer.mozilla.org/docs/Web/API/XPathResult/booleanValue)
*/
  booleanValue: bool,
  /**
[Read more on MDN](https://developer.mozilla.org/docs/Web/API/XPathResult/singleNodeValue)
*/
  singleNodeValue: Null.t<DOMTree.node>,
  /**
[Read more on MDN](https://developer.mozilla.org/docs/Web/API/XPathResult/invalidIteratorState)
*/
  invalidIteratorState: bool,
  /**
[Read more on MDN](https://developer.mozilla.org/docs/Web/API/XPathResult/snapshotLength)
*/
  snapshotLength: int,
}

/**
[Read more on MDN](https://developer.mozilla.org/docs/Web/API/XPathResult/iterateNext)
*/
@send
external iterateNext: t => DOMTree.node = "iterateNext"

/**
[Read more on MDN](https://developer.mozilla.org/docs/Web/API/XPathResult/snapshotItem)
*/
@send
external snapshotItem: (t, int) => DOMTree.node = "snapshotItem"
