// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Event$Event from "./Event.js";

function Impl(T) {
  Event$Event.Impl({});
  return {};
}

Event$Event.Impl({});

export {
  Impl,
}
/*  Not a pure module */
