// Generated by ReScript, PLEASE EDIT WITH CARE


let DOMStringList = {};

let Location = {};

let Navigator = {};

let DOMTokenList = {};

let NamedNodeMap = {};

let CustomElementRegistry = {};

let ScreenOrientation = {};

let DocumentTimeline = {};

let Node = {};

let NodeList = {};

let NodeListOf = {};

let Element = {};

let ShadowRoot = {};

let HTMLCollection = {};

let HTMLCollectionOf = {};

let HTMLFormControlsCollection = {};

let HTMLElement = {};

let HTMLHeadElement = {};

let HTMLFormElement = {};

let HTMLImageElement = {};

let HTMLEmbedElement = {};

let HTMLAnchorElement = {};

let HTMLAreaElement = {};

let HTMLScriptElement = {};

let DOMImplementation = {};

let Document = {};

let Window = {};

let CharacterData = {};

let DocumentFragment = {};

let StylePropertyMapReadOnly = {};

let DOMRectReadOnly = {};

let DOMRect = {};

let DOMRectList = {};

let ElementInternals = {};

let Text = {};

let Comment = {};

let Range = {};

let NodeFilter = {};

let NodeIterator = {};

let TreeWalker = {};

let CaretPosition = {};

let Selection = {};

let MediaQueryList = {};

let MediaList = {};

let IdleDeadline = {};

let CSSStyleValue = {};

let FileList = {};

let FileSystemDirectoryReader = {};

let TimeRanges = {};

let TextTrackList = {};

let CSSStyleSheet = {};

let CSSRuleList = {};

let CSSStyleDeclaration = {};

let HTMLTableElement = {};

let HTMLTableCaptionElement = {};

let HTMLTableSectionElement = {};

let HTMLTableCellElement = {};

let HTMLTableRowElement = {};

let HTMLButtonElement = {};

let HTMLLabelElement = {};

let HTMLTextAreaElement = {};

let HTMLOutputElement = {};

let HTMLInputElement = {};

let HTMLDataListElement = {};

let HTMLSelectElement = {};

let HTMLOptionElement = {};

let HTMLOptionsCollection = {};

let HTMLMediaElement = {};

let HTMLAudioElement = {};

let HTMLBaseElement = {};

let HTMLBodyElement = {};

let HTMLBRElement = {};

let HTMLCanvasElement = {};

let HTMLDataElement = {};

let HTMLDialogElement = {};

let HTMLDivElement = {};

let HTMLDListElement = {};

let HTMLFieldSetElement = {};

let HTMLFrameSetElement = {};

let HTMLHeadingElement = {};

let HTMLHRElement = {};

let HTMLHtmlElement = {};

let HTMLIFrameElement = {};

let HTMLLegendElement = {};

let HTMLLIElement = {};

let HTMLLinkElement = {};

let HTMLMapElement = {};

let HTMLMenuElement = {};

let HTMLMetaElement = {};

let HTMLMeterElement = {};

let HTMLModElement = {};

let HTMLObjectElement = {};

let HTMLOListElement = {};

let HTMLOptGroupElement = {};

let HTMLParagraphElement = {};

let HTMLPictureElement = {};

let HTMLPreElement = {};

let HTMLProgressElement = {};

let HTMLQuoteElement = {};

let HTMLSourceElement = {};

let HTMLSpanElement = {};

let HTMLStyleElement = {};

let HTMLTemplateElement = {};

let HTMLTimeElement = {};

let HTMLTitleElement = {};

let HTMLTrackElement = {};

let HTMLUListElement = {};

let HTMLVideoElement = {};

export {
  DOMStringList,
  Location,
  Navigator,
  DOMTokenList,
  NamedNodeMap,
  CustomElementRegistry,
  ScreenOrientation,
  DocumentTimeline,
  Node,
  NodeList,
  NodeListOf,
  Element,
  ShadowRoot,
  HTMLCollection,
  HTMLCollectionOf,
  HTMLFormControlsCollection,
  HTMLElement,
  HTMLHeadElement,
  HTMLFormElement,
  HTMLImageElement,
  HTMLEmbedElement,
  HTMLAnchorElement,
  HTMLAreaElement,
  HTMLScriptElement,
  DOMImplementation,
  Document,
  Window,
  CharacterData,
  DocumentFragment,
  StylePropertyMapReadOnly,
  DOMRectReadOnly,
  DOMRect,
  DOMRectList,
  ElementInternals,
  Text,
  Comment,
  Range,
  NodeFilter,
  NodeIterator,
  TreeWalker,
  CaretPosition,
  Selection,
  MediaQueryList,
  MediaList,
  IdleDeadline,
  CSSStyleValue,
  FileList,
  FileSystemDirectoryReader,
  TimeRanges,
  TextTrackList,
  CSSStyleSheet,
  CSSRuleList,
  CSSStyleDeclaration,
  HTMLTableElement,
  HTMLTableCaptionElement,
  HTMLTableSectionElement,
  HTMLTableCellElement,
  HTMLTableRowElement,
  HTMLButtonElement,
  HTMLLabelElement,
  HTMLTextAreaElement,
  HTMLOutputElement,
  HTMLInputElement,
  HTMLDataListElement,
  HTMLSelectElement,
  HTMLOptionElement,
  HTMLOptionsCollection,
  HTMLMediaElement,
  HTMLAudioElement,
  HTMLBaseElement,
  HTMLBodyElement,
  HTMLBRElement,
  HTMLCanvasElement,
  HTMLDataElement,
  HTMLDialogElement,
  HTMLDivElement,
  HTMLDListElement,
  HTMLFieldSetElement,
  HTMLFrameSetElement,
  HTMLHeadingElement,
  HTMLHRElement,
  HTMLHtmlElement,
  HTMLIFrameElement,
  HTMLLegendElement,
  HTMLLIElement,
  HTMLLinkElement,
  HTMLMapElement,
  HTMLMenuElement,
  HTMLMetaElement,
  HTMLMeterElement,
  HTMLModElement,
  HTMLObjectElement,
  HTMLOListElement,
  HTMLOptGroupElement,
  HTMLParagraphElement,
  HTMLPictureElement,
  HTMLPreElement,
  HTMLProgressElement,
  HTMLQuoteElement,
  HTMLSourceElement,
  HTMLSpanElement,
  HTMLStyleElement,
  HTMLTemplateElement,
  HTMLTimeElement,
  HTMLTitleElement,
  HTMLTrackElement,
  HTMLUListElement,
  HTMLVideoElement,
}
/* No side effect */
