// Generated by ReScript, PLEASE EDIT WITH CARE


let DOMStringList = {};

let Location = {};

let Navigator = {};

let DOMTokenList = {};

let NamedNodeMap = {};

let CustomElementRegistry = {};

let ScreenOrientation = {};

let DocumentTimeline = {};

let Node = {};

let NodeList = {};

let NodeListOf = {};

let Element = {};

let ShadowRoot = {};

let HTMLCollection = {};

let HTMLCollectionOf = {};

let HTMLFormControlsCollection = {};

let HTMLElement = {};

let HTMLHeadElement = {};

let HTMLFormElement = {};

let HTMLImageElement = {};

let HTMLEmbedElement = {};

let HTMLAnchorElement = {};

let HTMLAreaElement = {};

let HTMLScriptElement = {};

let DOMImplementation = {};

let Document = {};

let Window = {};

let CharacterData = {};

let StylePropertyMapReadOnly = {};

let DOMRectReadOnly = {};

let DOMRect = {};

let DOMRectList = {};

let ElementInternals = {};

let DocumentFragment = {};

let Text = {};

let Comment = {};

let Range = {};

let NodeFilter = {};

let NodeIterator = {};

let TreeWalker = {};

let CaretPosition = {};

let Selection = {};

let MediaQueryList = {};

let MediaList = {};

let IdleDeadline = {};

let CSSStyleValue = {};

let FileList = {};

let FileSystemDirectoryReader = {};

let CSSStyleSheet = {};

let CSSRuleList = {};

let CSSStyleDeclaration = {};

let HTMLTableElement = {};

let HTMLTableCaptionElement = {};

let HTMLTableSectionElement = {};

let HTMLTableCellElement = {};

let HTMLTableRowElement = {};

let HTMLButtonElement = {};

let HTMLLabelElement = {};

let HTMLTextAreaElement = {};

let HTMLOutputElement = {};

let HTMLInputElement = {};

let HTMLDataListElement = {};

let HTMLSelectElement = {};

let HTMLOptionElement = {};

let HTMLOptionsCollection = {};

export {
  DOMStringList,
  Location,
  Navigator,
  DOMTokenList,
  NamedNodeMap,
  CustomElementRegistry,
  ScreenOrientation,
  DocumentTimeline,
  Node,
  NodeList,
  NodeListOf,
  Element,
  ShadowRoot,
  HTMLCollection,
  HTMLCollectionOf,
  HTMLFormControlsCollection,
  HTMLElement,
  HTMLHeadElement,
  HTMLFormElement,
  HTMLImageElement,
  HTMLEmbedElement,
  HTMLAnchorElement,
  HTMLAreaElement,
  HTMLScriptElement,
  DOMImplementation,
  Document,
  Window,
  CharacterData,
  StylePropertyMapReadOnly,
  DOMRectReadOnly,
  DOMRect,
  DOMRectList,
  ElementInternals,
  DocumentFragment,
  Text,
  Comment,
  Range,
  NodeFilter,
  NodeIterator,
  TreeWalker,
  CaretPosition,
  Selection,
  MediaQueryList,
  MediaList,
  IdleDeadline,
  CSSStyleValue,
  FileList,
  FileSystemDirectoryReader,
  CSSStyleSheet,
  CSSRuleList,
  CSSStyleDeclaration,
  HTMLTableElement,
  HTMLTableCaptionElement,
  HTMLTableSectionElement,
  HTMLTableCellElement,
  HTMLTableRowElement,
  HTMLButtonElement,
  HTMLLabelElement,
  HTMLTextAreaElement,
  HTMLOutputElement,
  HTMLInputElement,
  HTMLDataListElement,
  HTMLSelectElement,
  HTMLOptionElement,
  HTMLOptionsCollection,
}
/* No side effect */
