// Generated by ReScript, PLEASE EDIT WITH CARE


let MediaKeySystemAccess = {};

let MediaKeys = {};

let MediaKeyStatusMap = {};

let MediaKeySession = {};

export {
  MediaKeySystemAccess,
  MediaKeys,
  MediaKeyStatusMap,
  MediaKeySession,
}
/* No side effect */
