// Generated by ReScript, PLEASE EDIT WITH CARE


let EventTarget = {};

let Event = {};

let AbortController = {};

let AbortSignal = {};

export {
  EventTarget,
  Event,
  AbortController,
  AbortSignal,
}
/* No side effect */
