// Generated by ReScript, PLEASE EDIT WITH CARE


let FileSystemEntry = {};

let FileSystemDirectoryEntry = {};

let FileSystemDirectoryReader = {};

export {
  FileSystemEntry,
  FileSystemDirectoryEntry,
  FileSystemDirectoryReader,
}
/* No side effect */
