// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Blob$WebAPI from "./File/Blob.js";

Blob$WebAPI.Impl({});

function isInstanceOf(param) {
  return (param instanceof File);
}

export {
  isInstanceOf,
}
/*  Not a pure module */
