// Generated by ReScript, PLEASE EDIT WITH CARE


let Blob = {};

let ReadableStream = {};

let WritableStream = {};

let WritableStreamDefaultController = {};

export {
  Blob,
  ReadableStream,
  WritableStream,
  WritableStreamDefaultController,
}
/* No side effect */
