// Generated by ReScript, PLEASE EDIT WITH CARE


let Blob = {};

let ReadableStream = {};

let WritableStream = {};

let WritableStreamDefaultController = {};

let File = {};

let FileSystemHandle = {};

let FileSystemDirectoryHandle = {};

let FileSystemFileHandle = {};

let FileSystemWritableFileStream = {};

export {
  Blob,
  ReadableStream,
  WritableStream,
  WritableStreamDefaultController,
  File,
  FileSystemHandle,
  FileSystemDirectoryHandle,
  FileSystemFileHandle,
  FileSystemWritableFileStream,
}
/* No side effect */
