// Generated by ReScript, PLEASE EDIT WITH CARE


let Geolocation = {};

let GeolocationCoordinates = {};

let GeolocationPosition = {};

export {
  Geolocation,
  GeolocationCoordinates,
  GeolocationPosition,
}
/* No side effect */
