// Generated by ReScript, PLEASE EDIT WITH CARE


let IDBFactory = {};

let IDBDatabase = {};

let IDBTransaction = {};

let IDBObjectStore = {};

let IDBIndex = {};

export {
  IDBFactory,
  IDBDatabase,
  IDBTransaction,
  IDBObjectStore,
  IDBIndex,
}
/* No side effect */
