// Generated by ReScript, PLEASE EDIT WITH CARE


let MediaDevices = {};

let MediaDeviceInfo = {};

let MediaStream = {};

let MediaStreamTrack = {};

export {
  MediaDevices,
  MediaDeviceInfo,
  MediaStream,
  MediaStreamTrack,
}
/* No side effect */
