// Generated by ReScript, PLEASE EDIT WITH CARE


let Performance = {};

let PerformanceEntry = {};

let PerformanceMark = {};

export {
  Performance,
  PerformanceEntry,
  PerformanceMark,
}
/* No side effect */
