// Generated by ReScript, PLEASE EDIT WITH CARE


let ServiceWorker = {};

let NavigationPreloadManager = {};

let ServiceWorkerRegistration = {};

let ServiceWorkerContainer = {};

export {
  ServiceWorker,
  NavigationPreloadManager,
  ServiceWorkerRegistration,
  ServiceWorkerContainer,
}
/* No side effect */
