// Generated by ReScript, PLEASE EDIT WITH CARE


let ServiceWorker = {};

let NavigationPreloadManager = {};

let ServiceWorkerRegistration = {};

let ServiceWorkerContainer = {};

let CacheStorage = {};

let Cache = {};

export {
  ServiceWorker,
  NavigationPreloadManager,
  ServiceWorkerRegistration,
  ServiceWorkerContainer,
  CacheStorage,
  Cache,
}
/* No side effect */
