// Generated by ReScript, PLEASE EDIT WITH CARE


let AudioBuffer = {};

let AudioProcessingEvent = {};

let MediaStreamTrack = {};

let OfflineAudioCompletionEvent = {};

let AudioNode = {};

let BaseAudioContext = {};

let BiquadFilterNode = {};

let AudioListener = {};

let AudioParam = {};

let AudioScheduledSourceNode = {};

let AudioBufferSourceNode = {};

let ChannelMergerNode = {};

let ChannelSplitterNode = {};

let ConstantSourceNode = {};

let ConvolverNode = {};

let DelayNode = {};

let DynamicsCompressorNode = {};

let GainNode = {};

let IIRFilterNode = {};

let OscillatorNode = {};

let PannerNode = {};

let AnalyserNode = {};

let PeriodicWave = {};

let StereoPannerNode = {};

let WaveShaperNode = {};

let AudioContext = {};

let MediaElementAudioSourceNode = {};

let MediaStream = {};

let MediaStreamAudioSourceNode = {};

let MediaStreamAudioDestinationNode = {};

let AudioWorkletNode = {};

let OfflineAudioContext = {};

export {
  AudioBuffer,
  AudioProcessingEvent,
  MediaStreamTrack,
  OfflineAudioCompletionEvent,
  AudioNode,
  BaseAudioContext,
  BiquadFilterNode,
  AudioListener,
  AudioParam,
  AudioScheduledSourceNode,
  AudioBufferSourceNode,
  ChannelMergerNode,
  ChannelSplitterNode,
  ConstantSourceNode,
  ConvolverNode,
  DelayNode,
  DynamicsCompressorNode,
  GainNode,
  IIRFilterNode,
  OscillatorNode,
  PannerNode,
  AnalyserNode,
  PeriodicWave,
  StereoPannerNode,
  WaveShaperNode,
  AudioContext,
  MediaElementAudioSourceNode,
  MediaStream,
  MediaStreamAudioSourceNode,
  MediaStreamAudioDestinationNode,
  AudioWorkletNode,
  OfflineAudioContext,
}
/* No side effect */
