// Generated by ReScript, PLEASE EDIT WITH CARE


let AudioBuffer = {};

let MediaStreamTrack = {};

let AudioNode = {};

let BaseAudioContext = {};

let BiquadFilterNode = {};

let AudioListener = {};

let AudioParam = {};

let AudioScheduledSourceNode = {};

let AudioBufferSourceNode = {};

let IIRFilterNode = {};

let OscillatorNode = {};

let PannerNode = {};

let AnalyserNode = {};

let AudioContext = {};

let MediaStream = {};

let OfflineAudioContext = {};

export {
  AudioBuffer,
  MediaStreamTrack,
  AudioNode,
  BaseAudioContext,
  BiquadFilterNode,
  AudioListener,
  AudioParam,
  AudioScheduledSourceNode,
  AudioBufferSourceNode,
  IIRFilterNode,
  OscillatorNode,
  PannerNode,
  AnalyserNode,
  AudioContext,
  MediaStream,
  OfflineAudioContext,
}
/* No side effect */
