// Generated by ReScript, PLEASE EDIT WITH CARE


let WebSocket = {};

let CloseEvent = {};

let MessagePort = {};

let MessageEvent = {};

export {
  WebSocket,
  CloseEvent,
  MessagePort,
  MessageEvent,
}
/* No side effect */
