// Generated by ReScript, PLEASE EDIT WITH CARE

import * as WorkerGlobalScope$WebAPI from "./WorkerGlobalScope.js";

function Impl(T) {
  WorkerGlobalScope$WebAPI.Impl({});
  return {};
}

WorkerGlobalScope$WebAPI.Impl({});

export {
  Impl,
}
/*  Not a pure module */
