// Generated by ReScript, PLEASE EDIT WITH CARE


let h = new Headers();

h.set("X-Test", "1");

let h2 = new Headers({
  "X-Vegetable": "Carrot"
});

let h3 = new Headers([
  [
    "X-Fruit",
    "Apple"
  ],
  [
    "X-Vegetable",
    "Carrot"
  ]
]);

console.log(h3.get("X-Fruit"));

export {
  h,
  h2,
  h3,
}
/* h Not a pure module */
