// Generated by ReScript, PLEASE EDIT WITH CARE


let req = new Request("https://example.com");

let req1 = new Request("https://example.com/api", {
  method: "POST",
  body: "hello"
});

let req2 = new Request(req1);

console.log(await req2.text());

export {
  req,
  req1,
  req2,
}
/* req Not a pure module */
