// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Int from "rescript/lib/es6/Int.js";
import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";

let button = document.querySelector("button");

let h2 = document.querySelector("h2");

if (button !== null && h2 !== null) {
  button.addEventListener("click", e => {
    console.log("Button clicked, " + e.button.toString());
    let text = h2.textContent;
    if (text === null) {
      h2.textContent = "1";
      return;
    }
    let number = Int.fromString(text, undefined);
    if (number !== undefined) {
      h2.textContent = (number + 1 | 0).toString();
    } else {
      h2.textContent = "1";
    }
  });
} else {
  console.log("Stuff not found");
}

let button$1 = button === null ? undefined : Primitive_option.some(button);

let h2$1 = h2 === null ? undefined : Primitive_option.some(h2);

export {
  button$1 as button,
  h2$1 as h2,
}
/* button Not a pure module */
