// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Option from "rescript/lib/es6/Option.js";
import * as Document$WebAPI from "../../src/DOMAPI/Document.js";
import * as FillStyle$WebAPI from "../../src/DOMAPI/FillStyle.js";

let myCanvas = Document$WebAPI.querySelector_htmlCanvasElement(document, "#myCanvas");

Option.forEach(myCanvas, myCanvas => {
  let ctx = myCanvas.getContext("2d");
  ctx.fillStyle = "red";
  ctx.fillRect(50, 50, 200, 200);
  ctx.fillStyle = "black";
  ctx.font = "2px Tahoma";
  ctx.textBaseline = "top";
  ctx.fillText("MY TEXT", 60, 60);
  let color = FillStyle$WebAPI.decode(ctx.fillStyle);
  switch (color.TAG) {
    case "String" :
      console.log("Color: " + color._0);
      return;
    case "CanvasGradient" :
      console.log("CanvasGradient");
      return;
    case "CanvasPattern" :
      console.log("CanvasPattern");
      return;
  }
});

export {
  myCanvas,
}
/* myCanvas Not a pure module */
