// Generated by ReScript, PLEASE EDIT WITH CARE


let myCanvas = document.getElementById("myCanvas");

let ctx = myCanvas.getContext("2d");

ctx.fillStyle = "red";

ctx.fillRect(50, 50, 200, 200);

ctx.fillStyle = "black";

ctx.font = "2px Tahoma";

ctx.textBaseline = "top";

ctx.fillText("MY TEXT", 60, 60);

export {
  myCanvas,
  ctx,
}
/* myCanvas Not a pure module */
