// Generated by ReScript, PLEASE EDIT WITH CARE


let imageData = new ImageData(new Uint8ClampedArray([]), 100, 100);

console.log(imageData.data.length);

export {
  imageData,
}
/* imageData Not a pure module */
