// Generated by ReScript, PLEASE EDIT WITH CARE


let location = document.location;

let href = location.href;

location.reload();

let a = 0;

export {
  location,
  href,
  a,
}
/* location Not a pure module */
