// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "rescript/lib/es6/Stdlib_Option.js";
import * as Document$WebAPI from "../../src/DOMAPI/Document.js";
import * as HTMLHeadingElement$WebAPI from "../../src/DOMAPI/HTMLHeadingElement.js";

Stdlib_Option.forEach(Document$WebAPI.querySelectorAsHeading(document, "h2"), heading => {
  heading.style.color = "red";
});

Stdlib_Option.forEach(Stdlib_Option.flatMap(Document$WebAPI.querySelectorAsHeading(document, "h2"), HTMLHeadingElement$WebAPI.tryParse), heading => {
  heading.style.color = "red";
});

/*  Not a pure module */
